# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b04ffb86d121fab9558d931073651cf724b1c652114c9734ba20232944f4c8a7046a924db2bd868b93b3669a9c788a17768a41be6fd2f26d23c1e878b15889a

test:
  secret_key_base: fcf68072b030ebba5ef010c98dc1364ea92d6dc77fa308ab564ddb43a34a8642ece1618c56606d2ab82889078ebde3788507dd83d3624811fa0c2fe088543e9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
